/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IRiArrowLeftLine: typeof import('~icons/ri/arrow-left-line')['default']
    IRiTimer2Line: typeof import('~icons/ri/timer2-line')['default']
    IRiUserFill: typeof import('~icons/ri/user-fill')['default']
    IRiUserLine: typeof import('~icons/ri/user-line')['default']
    NBtn: typeof import('naive-ui')['NBtn']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NH4: typeof import('naive-ui')['NH4']
    NH5: typeof import('naive-ui')['NH5']
    NH6: typeof import('naive-ui')['NH6']
    NIcon: typeof import('naive-ui')['NIcon']
    NImg: typeof import('naive-ui')['NImg']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NP: typeof import('naive-ui')['NP']
    NSpace: typeof import('naive-ui')['NSpace']
    NTable: typeof import('naive-ui')['NTable']
    NTbody: typeof import('naive-ui')['NTbody']
    NTd: typeof import('naive-ui')['NTd']
    NText: typeof import('naive-ui')['NText']
    NTh: typeof import('naive-ui')['NTh']
    NThead: typeof import('naive-ui')['NThead']
    NTr: typeof import('naive-ui')['NTr']
    PTest: typeof import('./components/p-test.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
